import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={`${styles.description} ${styles.flexContainer}`}>
          <div>
            <a
              href="https://loanscape.ai"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Image
                src="/logo.svg"
                alt="loanscape Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
          <p>
            Coming Soon&nbsp;
            <code className={styles.code}>Q3 2022</code>
          </p>
        </div>

        <div className={`${styles.center} ${styles.headlines}`}>
          <h1 className={styles.mainHeadline}>Building The Future of Mortgage Technology.</h1>
        </div>
      </main>
    </>
  )
}
